---
- hosts: all
  connection: local
  gather_facts: true
  name: Example snapshot comparison playbook

  vars:
    provider:
      ip_address: "{{ panorama_ip_address }}"
      username: "{{ username | default(lookup('env', 'ANSIBLE_NET_USERNAME')) }}"
      password: "{{ password | default(lookup('env', 'ANSIBLE_NET_PASSWORD')) }}"
      serial_number: "{{ serialno }}"
    version: 11.2.7-h4

  roles:
    - role: upgrade
      name: Run an upgrade