---
- hosts: all
  connection: local
  gather_facts: true
  name: Example snapshot comparison playbook

  vars:
    provider:
      ip_address: "{{ panorama_ip_address }}"
      username: "{{ username | default(lookup('env', 'ANSIBLE_NET_USERNAME')) }}"
      password: "{{ password | default(lookup('env', 'ANSIBLE_NET_PASSWORD')) }}"
      serial_number: "{{ serialno }}"
    snapshot_directory: "./snapshots"

  roles:
    - role: take_snapshot
      name: Take the pre-upgrade snapshot
      vars:
        snapshot_filename: "pre_upgrade_snapshot_{{ serialno }}"

    - role: take_snapshot
      name: Take the pre-upgrade snapshot for the peer
      vars:
        snapshot_filename: "pre_upgrade_snapshot_{{ peer_serialno }}"
      when:
        - peer_serialno is defined

    - role: take_snapshot
      name: Take the post-upgrade snapshot
      vars:
        snapshot_filename: "post_upgrade_snapshot_{{ serialno }}"

    - role: take_snapshot
      name: Take the post-upgrade snapshot for the peer
      vars:
        snapshot_filename: "post_upgrade_snapshot_{{ peer_serialno }}"
      when:
        - peer_serialno is defined

    # This is where we would run the upgrade of passive

    - role: snapshot_report_from_files
      name: Compare the two snapshot reports from the main
      vars:
        left_snapshot: "pre_upgrade_snapshot_{{ serialno }}"
        right_snapshot: "post_upgrade_snapshot_{{ serialno }}"

    - role: snapshot_report_from_files
      name: Compare the two snapshot reports from the passive
      vars:
        left_snapshot: "pre_upgrade_snapshot_{{ peer_serialno }}"
        right_snapshot: "post_upgrade_snapshot_{{ peer_serialno }}"
      when:
        - peer_serialno is defined